# Generated by Django 3.1 on 2020-08-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('produttore', models.CharField(max_length=30)),
                ('nome_prodotto', models.CharField(max_length=30)),
                ('descrizione_prodotto', models.CharField(max_length=100)),
                ('prezzo_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prezzo_pezzi', models.DecimalField(decimal_places=2, max_digits=7)),
                ('informazioni', models.CharField(max_length=300)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='')),
                ('flag_pezzi', models.BooleanField(blank=True, default=False, null=True)),
                ('unità_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unità_misura', models.CharField(max_length=10)),
            ],
        ),
    ]
