# Generated by Django 3.1 on 2020-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200820_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dta_ins', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('indirizzo', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('città', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('orario_consegna', models.CharField(max_length=50)),
                ('costo_consegna', models.CharField(max_length=50)),
                ('note', models.TextField()),
            ],
        ),
    ]
