# Generated by Django 3.1 on 2020-08-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ordini'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordini',
            options={'verbose_name': 'Ordini', 'verbose_name_plural': 'Ordini'},
        ),
    ]
