# Generated by Django 3.1 on 2020-08-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200820_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordini',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ordini_dettaglio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=30)),
                ('prezzo_pezzi', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prezzo_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('q_pezzi', models.IntegerField(default=1)),
                ('q_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unità_misura', models.CharField(max_length=10)),
                ('id_ordine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.ordini')),
            ],
            options={
                'verbose_name': 'Ordini Dettaglio',
                'verbose_name_plural': 'Ordini Dettaglio',
            },
        ),
    ]
