# Generated by Django 3.1 on 2020-08-21 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200820_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('categoria',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='prodotti',
            options={'ordering': ('nome_prodotto',), 'verbose_name': 'Prodotti', 'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotti',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prodotti',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='store.categoria'),
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='nome_prodotto',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterIndexTogether(
            name='prodotti',
            index_together={('id', 'slug')},
        ),
    ]
