# Generated by Django 3.1 on 2020-08-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200821_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordini_dettaglio',
            name='id_ordine',
        ),
        migrations.DeleteModel(
            name='Ordini',
        ),
        migrations.DeleteModel(
            name='Ordini_dettaglio',
        ),
    ]
