# Generated by Django 3.1 on 2020-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200824_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoConsegna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Località', models.CharField(max_length=30)),
                ('Importo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Località',
                'verbose_name_plural': 'Località',
                'ordering': ('Località',),
            },
        ),
    ]
