# Generated by Django 3.1 on 2020-09-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orarioconsegna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orarioconsegna',
            options={'verbose_name': 'Orario', 'verbose_name_plural': 'Orari'},
        ),
    ]
