# Generated by Django 3.1 on 2020-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_parametri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametri',
            name='Valore',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
