# Generated by Django 3.1 on 2020-08-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0010_auto_20200824_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('indirizzo', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('città', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('orario_consegna', models.CharField(max_length=50)),
                ('costo_consegna', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('gestito', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ordini',
                'verbose_name_plural': 'Ordini',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ordini_dettaglio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_pezzi', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prezzo_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('q_pezzi', models.PositiveIntegerField(default=1)),
                ('q_quantità', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unità_misura', models.CharField(max_length=10)),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordini')),
                ('nome_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.prodotti')),
            ],
            options={
                'verbose_name': 'Ordini Dettaglio',
                'verbose_name_plural': 'Ordini Dettaglio',
            },
        ),
    ]
