# Generated by Django 3.1 on 2020-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordini_dettaglio',
            name='prezzo_pezzi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ordini_dettaglio',
            name='q_pezzi',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordini_dettaglio',
            name='unità_misura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
