# Generated by Django 3.1 on 2020-10-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200824_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordini',
            name='costo_consegna',
        ),
    ]
